wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1676922567.325794
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      - 24
      4: 3.7.15
      5: 0.13.10
      8:
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 512
dataset:
  desc: null
  value: SCC
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
